DATA_PATH = "data/AEP_hourly.csv"

MODEL_PATH = "models/random_forest.pkl"

DATASET = "grid"  # options: grid, building
MODE = "grid"     # options: grid, factory
UNIT_CONVERSION = True  # applied for building dataset
RUN_COMPARISON = False

FORECAST_HORIZON = 72
FORECAST_HORIZONS = [24, 48, 72, 168]
USE_PIPELINE_ORCHESTRATOR = False
ENABLE_EXPLAINABILITY = True
ENABLE_ANOMALY_DETECTION = True
ENABLE_DATA_INGESTION_SCAN = True
ENABLE_KAGGLE_DOWNLOAD = False
ENABLE_AUTO_RETRAIN = True
AUTO_RETRAIN_INTERVAL_HOURS = 24
AUTOML_TRIALS = 30
ENABLE_AUTOML_ENGINE = True
AUTOML_ENGINE_MAX_TRIALS = 30

PEAK_PERCENTILE = 0.9

SHIFT_MIN = 0.10
SHIFT_MAX = 0.20

PRICE_PER_MWH_RUB = 7500
PRICE_PER_MWH_FACTORY_RUB = 6500
CO2_FACTOR = 0.45
CURRENCY = "RUB"
